name: Build Custom AMI
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  packer_build:
    runs-on: ubuntu-latest      
    defaults:
      working-directory: packer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: 1.13.1
      
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
            
      - name: Packer Init
        run: |
          packer init .
      
      - name: Packer Build
        run: |
          packer build \
            -var "role_arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Packer-Role" \
            .

