name: Build Custom AMI
on:
  workflow_dispatch:
    inputs:
      job_selection:
        type: choice
        description: "Select which jobs to run"
        options:
          - all
          - packer_build_only
          - terraform_deploy_only
          - terraform_destroy_only
        default: all
        required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  packer_build:
    if: github.event.inputs.job_selection == 'all' || github.event.inputs.job_selection == 'packer_build_only'
    runs-on: ubuntu-latest      
    defaults:
      run:
        shell: bash
        working-directory: packer
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-role

      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Install packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          packer_version: 1.13.1
      
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
            
      - name: Packer Init
        run: |
          packer init .
      
      - name: Packer Build
        run: |
          packer build \
            -var "role_arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Packer-Role" \
            .

  terraform_deploy:
    if: github.event.inputs.job_selection == 'all' || github.event.inputs.job_selection == 'terraform_deploy_only'
    runs-on: ubuntu-latest
    env: 
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-role

      - name: Checkout code
        uses: actions/Checkout@v4.2.2

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  terraform_destroy:
    if: github.event.inputs.job_selection == 'all' || github.event.inputs.job_selection == 'terraform_destroy_only'
    runs-on: ubuntu-latest
    env: 
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-role
      
      - name: Checkout code
        uses: actions/Checkout@v4.2.2
      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.1
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      
