name: Build Custom AMI
on:
  workflow_dispatch:

jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install packer
        uses: hashicorp/setup-packer@v3
      
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
            
      - name: Packer Init
        run: |
          cd packer
          packer init .
      
      - name: Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build -var "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Packer-Role" .

