name: Build Custom AMI
on:
  workflow_dispatch:
    inputs:
      job_selection:
        type: choice
        desctctiption: "Select which jobs to run"
        options:
          - all
          - packer_build_only
          - terraform_deploy_only
        default: all
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  packer_build:
    if: github.event.inputs.job_selection == 'all' || github.event.inputs.job_selection == 'packer_build_only'
    runs-on: ubuntu-latest      
    defaults:
      run:
        shell: bash
        working-directory: packer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: 1.13.1
      
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
            
      - name: Packer Init
        run: |
          packer init .
      
      - name: Packer Build
        run: |
          packer build \
            -var "role_arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Packer-Role" \
            .

  terraform_deploy:
    if: github.event.inputs.job_selection == 'all' || github.event.inputs.job_selection == 'terraform_deploy_only'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
